name = "uniswap-lp-bot"
main = "src/index.ts"
compatibility_date = "2024-01-15"
account_id = "6e88edc0eaf17afb288908adcc3b8e9e"

[triggers]
crons = ["*/5 * * * *"]

[[kv_namespaces]]
binding = "LP_BOT_KV"
id = "2766b768b5cf49909e4f3dd17d5007f9"
preview_id = "660d02386393490bbea92fb98daf655b"

[[r2_buckets]]
binding = "lp_bot_historical"
bucket_name = "lp-bot-historical"

[vars]
ARBITRUM_RPC = "https://arb-mainnet.g.alchemy.com/v2/your-key"
POOL_ADDRESS = "0x88e6A0c2dDD26FEEb64F039a2c41296FcB3f5640"
NPM_ADDRESS = "0xC36442b4a4522E871399CD717aBDD847Ab11FE88"
POSITION_TOKEN_ID = "12345"
TELEGRAM_CHAT_ID = "your-chat-id"

# Strategy parameters (optional, defaults in code)
BAND_BPS = "10"
TIME_CAP_HOURS = "24"
FEE_GAS_MULTIPLE = "3"
GAS_COST_USD = "2"